services:
  dev:
    image: dev:latest
    container_name: dev
    build:
      context: .
    volumes:
      - dev_volume:/workspace
      - ~/docker_ssh_keys:/root/.ssh
      - ./github-setup.sh:/workspace/github-setup.sh
    ports:
      - "8080:8080"
      - "3000:3000"
      - "80:80"
      - "8000:8000"
      - "4200:4200"
    entrypoint: ["zsh", "-c", "tail -f /dev/null"]

volumes:
  dev_volume:
    driver: local
